apiVersion: v1
kind: Pod
metadata:
  name: panoseti-service-pod
  labels:
    app: panoseti-service
spec:
  containers:
  - name: ubuntu
    image: ubuntu:24.04
    command: ["/bin/bash", "-c", "sleep infinity"]

  - name: redis
    image: redis:7
    ports:
    - containerPort: 6379

  - name: influxdb
    image: influxdb:2.7
    ports:
    - containerPort: 8086

  - name: grafana
    image: grafana/grafana:latest
    ports:
    - containerPort: 3000

  - name: apache
    image: httpd:2.4
    ports:
    - containerPort: 80
