apiVersion: v1
kind: Pod
metadata:
  name: panoseti-pod
spec:
  hostname: headnode
  containers:
    - name: ubuntu
      image: ghcr.io/liuweiseu/ubuntu-aarch64:24.04-v1.0
      command: [ "sleep", "infinity" ]
      workingDir: /home/panoseti
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - mountPath: /home/panoseti/panoseti
          name: panoseti-vol

    - name: redis
      image: docker.io/library/redis:7

    - name: influxdb
      image: docker.io/library/influxdb:2.7
      ports:
        - containerPort: 8086
          hostPort: 8086

    - name: grafana
      image: docker.io/grafana/grafana:latest
      ports:
        - containerPort: 3000
          hostPort: 3000

    - name: apache
      image: docker.io/library/httpd:latest
      ports:
        - containerPort: 80
          hostPort: 8080

  volumes:
    - name: panoseti-vol
      hostPath:
        path: /home/wei/Projects/panoseti
        type: Directory
