apiVersion: v1
kind: Pod
metadata:
  name: panoseti-pod
  labels:
    app: panoseti-service
spec:
  hostname: headnode
  containers:
  - name: ubuntu
    image: ghcr.io/liuweiseu/ubuntu-aarch64:24.04-v1.0
    command: ["/bin/bash", "-c", "sleep infinity"]
    workingDir: /home/panoseti
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    volumeMounts:
      - mountPath: /home/panoseti/panoseti
        name: panoseti-volume

  - name: redis
    image: redis:7
    ports:
    - containerPort: 6379

  - name: influxdb
    image: influxdb:2.7
    ports:
    - containerPort: 8086

  - name: grafana
    image: grafana/grafana:latest
    ports:
    - containerPort: 3000

  - name: apache
    image: httpd:2.4
    ports:
    - containerPort: 80
  volumes:
    - name: panoseti-volume
      hostPath:
        path: /mnt/data       
        type: Directory
