---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  type: NodePort
  selector:
    app: panoseti-service
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    nodePort: 31001
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
spec:
  type: NodePort
  selector:
    app: panoseti-service
  ports:
  - name: influxdb
    port: 8086
    targetPort: 8086
    nodePort: 31002
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
spec:
  type: NodePort
  selector:
    app: panoseti-service
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
    nodePort: 31003
---
apiVersion: v1
kind: Service
metadata:
  name: apache-svc
spec:
  type: NodePort
  selector:
    app: panoseti-service
  ports:
  - name: apache
    port: 80
    targetPort: 80
    nodePort: 31004
